site_name: Notes by T. Kono
theme:
  name: material
  language: ja
  palette:
    primary: green
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.indexes
extra_css:
  - stylesheets/extra.css
nav:
  - Home: index.md
#  - 構造:
#    - structures/index.md
#    - transformTR.md
#  - シミュレーション:
#    - simulation/index.md
  - 計算機:
    - computing/index.md
    - C++ 基礎: computing/CppBasics.md
    - C++ オブジェクト指向: computing/CppOO.md
    - C++ メモリの扱い: computing/CppMemory.md
    - C++ STL: computing/CppStl.md
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
